### ISSUE TITLE
Consider removing Playground from Results + Implementation description

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-testing#427]
Arch call on Oct 6th:

Playground is a testing tool and not a thing or consumer. All results are null, so it is not taken into account for the report.
It has been suggested to remove it from the results.

**Comment by egekorkan** [comment]
I don't mind removing it from the architecture results since none of the assertions apply to it. I have said this in my PR but no one bothered to review it and now you want to remove it. It is a late review, so ok...

It is not a pure testing tool though. It can manipulate TDs to for example add and remove defaults and will be soon able to do some basic visualization of TDs.

As you see, it has a couple of pass assertions at https://github.com/w3c/wot-testing/blob/main/data/input_2022/TD/Playground/Playground.csv

**Comment by mmccool** [comment]
Discussion in testing call:
- There are some "pass" results in TD, where Playground is considered a "TD Processor" (eg. a validator and transformer - eg insert/remove default values, or convert to OpenAPI).  So we should keep that one.
- It *is* an implementation, of a TD processor.  So we should have an implementation description for it IMO in Arch.
- None of the assertions in Arch actually apply, though, so all the answers are null.  But it doesn't affect anything so I say we just keep it.

Resolution: don't remove this file from either Arch or TD results.  But we may want to update/refine the implementation description.
